model_config:
  forecast_horizon: 12  # months
  validation_split: 0.2
  test_split: 0.1
  random_state: 42

data_config:
  chunk_size: 100000  # for processing large datasets
  min_samples_per_category: 100
  date_format: "%Y-%m-%d"
  
features:
  include_holidays: true
  include_seasonality: true
  include_promotions: true
  lag_features: [1, 3, 6, 12]  # months
  rolling_window_sizes: [3, 6, 12]  # months
  
models:
  xgboost:
    n_estimators: 1000
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
    
  lightgbm:
    n_estimators: 1000
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.8
    feature_fraction: 0.8
    
  prophet:
    seasonality_mode: 'multiplicative'
    yearly_seasonality: true
    weekly_seasonality: false
    daily_seasonality: false
    changepoint_prior_scale: 0.05
    
  neural_network:
    hidden_layers: [128, 64, 32]
    epochs: 100
    batch_size: 32
    learning_rate: 0.001
    dropout: 0.2

interpretability:
  shap_sample_size: 1000
  lime_sample_size: 500
  top_features: 20